
local ranks = {
    "Aether Genesis Master Ninja",
    "Ancient Battle Legend",
    "Ancient Battle Master",
    "Apprentice",
    "Assassin",
    "Awakened Scythe Legend",
    "Awakened Scythemaster",
    "Chaos Legend",
    "Chaos Sensei",
    "Comet Strike Lion",
    "Cybernetic Azure Sensei",
    "Cybernetic Electro Legend",
    "Cybernetic Electro Master",
    "Dark Elements Blademaster",
    "Dark Elements Guardian",
    "Dark Sun Samurai Legend",
    "Dragon Evolution Form I",
    "Dragon Evolution Form II",
    "Dragon Evolution Form III",
    "Dragon Evolution Form IV",
    "Dragon Evolution Form V",
    "Dragon Master",
    "Dragon Warrior",
    "Eclipse Series Soul Master",
    "Elemental Legend",
    "Elite Series Master Legend",
    "Eternity Hunter",
    "Evolved Series Master Ninja",
    "Golden Sun Shuriken Legend",
    "Golden Sun Shuriken Master",
    "Grasshopper",
    "Immortal Assassin",
    "Infinity Legend",
    "Infinity Sensei",
    "Infinity Shadows Master",
    "Legendary Shadow Duelist",
    "Legendary Shadowmaster",
    "Lightning Storm Sensei",
    "Master Elemental Hero",
    "Master Legend Assassin",
    "Master Legend Sensei Hunter",
    "Master Legend Zephyr",
    "Master Ninja",
    "Master Of Elements",
    "Master Of Shadows",
    "Master Sensei",
    "Mythic Shadowmaster",
    "Ninja",
    "Ninja Legend",
    "Rising Shadow Eternal Ninja",
    "Rookie",
    "Samurai",
    "Sensei",
    "Shadow",
    "Shadow Chaos Assassin",
    "Shadow Chaos Legend",
    "Shadow Legend",
    "Shadow Storm Sensei",
    "Skyblade Ninja Master",
    "Skystorm Series Samurai Legend",
    "Starstrike Master Sensei",
    "Ultra Genesis Shadow"
}
